### ISSUE TITLE
File not found error when running lambda

### ISSUE THREAD

**Issue by guilherme-srsantos** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#114]
I created a simple project using the EmptyFunction template, added this package and puppeteer and when I try to execute the function I get this error in the cloudwatch logs:

Could not find file '/var/task/aws.tar.br'.

I assume that the error happens when the function tries to create the launcher, other than that I don't really know what could be happening.

**Comment by brianfeucht** [comment]
@guilherme-srsantos  can you please share which Architecture and Runtime you are running into this problem with?

**Comment by brianfeucht** [comment]
Feel free to reopen with more details
