### ISSUE TITLE
Failed to launch browser! Version `NSSUTIL_3.82' not found

### ISSUE THREAD

**Issue by svope** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#129]
Hi,

first of all thank you for this project!

I just found that there could be potentionally an issue with lauching PuppeteerSharp with chromium related to order of paths in LD_LIBRARY_PATH environment var.

I'm using @sparticuz/chromium": "122.0.0" and "PuppeteerSharp" Version="15.0.0"
My folder structure (S3 bucket with zip -> lambda layer -> used by lambda function) on AWS Lambda is:
Files in /opt dir:
/opt/chromium
/opt/libEGL.so
/opt/libGLESv2.so
/opt/libvk_swiftshader.so
/opt/libvulkan.so.1
/opt/vk_swiftshader_icd.json
/opt/.fonts/font.conf
/opt/.fonts/fonts.conf
/opt/lib/libexpat.so.1
/opt/lib/libnss3.so
/opt/lib/libnssutil3.so
/opt/lib/libsoftokn3.so
/opt/lib/libsqlite3.so.0
/opt/lib/libuuid.so.1
/opt/.fonts/fonts/Open_Sans/OFL.txt
/opt/.fonts/fonts/Open_Sans/OpenSans-Bold.ttf
/opt/.fonts/fonts/Open_Sans/OpenSans-Italic.ttf
/opt/.fonts/fonts/Open_Sans/OpenSans-Light.ttf
/opt/.fonts/fonts/Open_Sans/OpenSans-Regular.ttf
-> nothing special here

When my LD_LIBRARY_PATH is set to:
"/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib:**/opt/lib**"
I get this exception:
PuppeteerSharp.ProcessException: Failed to launch browser! /opt/chromium: /lib64/libnssutil3.so: version `NSSUTIL_3.82' not found (required by /opt/lib/libnss3.so)

When I put "/opt/lib" as the first folder:
"**/opt/lib**:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:"
Everything works fine (I actually don't know why)

I found this tip here:
https://github.com/alixaxel/chrome-aws-lambda/issues/37#issuecomment-544396375

Maybe this could be helpful for somebody or could be made into a pull request :)

Have a nice day!

**Comment by brianfeucht** [comment]
Thanks for the note!  I was hoping this might help with an issue we are running into on AL2023.   However it doesn't seem to have fixed anything.

Worth noting this lib drops all the chromium bins into `/tmp` since we are not using a layer.

https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/pull/123/commits/d02ad140af8f921d202321ca873080c9c7c53acd
