### ISSUE TITLE
Where to get the latest AWS Blink binaries to check the HTML to PDF Conversion in AWS .NET 8.0

### ISSUE THREAD

**Issue by sk02v** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#132]
I tried to convert the HTML to PDF conversion in the Net 8.0 target framework version, but we could not convert it. So can you please share the details of where to get the latest blink binaries? or any other suggestion to convert in net 8.0 al2023.

**Comment by brianfeucht** [comment]
I'm not sure what you mean by blink binaries.

We have an open issue and PR to get this lib working on AL2023.  There is currently an issue where chromium crashes when navigating to a webpage.  I haven't figured out the solution yet, but the crash is reproduceable locally using docker.  Happy to accept a PR if you are able to figure it out.

See: 
- https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/issues/122
- https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/pull/123
