### ISSUE TITLE
Archive files should be in a separate directory 

### ISSUE THREAD

**Issue by AleksandrsJakovlevsVisma** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#135]
Currently, in the solution explorer, .br files appear in the root. Can we make them appear in a separate directory for aesthetic reasons?

**Comment by brianfeucht** [comment]
@AleksandrsJakovlevsVisma this is not something I'll end up prioritizing.  I'm not opposed but you'll need to come up with a different approach and submit a PR.

**Comment by AleksandrsJakovlevsVisma** [comment]
@brianfeucht I can create a PR, will you give me access?

**Comment by brianfeucht** [comment]
You have all the access you need to fork, branch, and submit a PR

This gist has some great details on how to do that
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by AleksandrsJakovlevsVisma** [comment]
@brianfeucht Thanks, never done that before.

https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/pull/138
https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/pull/139
