### ISSUE TITLE
Fails to find chromium.br

### ISSUE THREAD

**Issue by cbp123** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#41]
Hi,
Nice piece of code, thanks for putting this together.

I'm not sure why ChromiumExtractor looks for "chromium-*.br"

The chromium.br file I have doesn't have the hyphen in it, so the Extractor doesn't find the file.

I changed it to look for just "chromium.br" and everything works fine now.

**Comment by brianfeucht** [comment]
Thanks for letting us know.  Looks like this fixed in a previous version and was undone due to a merge.
