### ISSUE TITLE
Chrome fails to launch in Lambda .NET Core 3.1 

### ISSUE THREAD

**Issue by brianfeucht** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#43]
Getting the following error when trying to launch in Lambda configured for .NET Core 3.1
`PuppeteerSharp.ChromiumProcessException: Failed to launch Chromium! /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

**Comment by DevGenesis95** [comment]
not able to run it with .net core 2.1 as well
