### ISSUE TITLE
Not able to build solution

### ISSUE THREAD

**Issue by DevGenesis95** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#48]
Not able to build the class library. Cannot integrate with a lambda function .Net 2.1.
![PuppeteerErr](https://user-images.githubusercontent.com/34500301/85018910-91a06580-b18b-11ea-8a86-97a47ecd89d5.png)

**Comment by brianfeucht** [comment]
`BrotliStream` was introduced in [`.NET Standard 1.4`](https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/) so should build in the project default `.NET Standard 2.1`

Can you provide the output of `dotnet --list-sdks` on your local machine?  Are you able to build this by running `.\build.ps1 -Target Build` from a command line?

**Comment by DevGenesis95** [comment]
Sure..
![sdkLists](https://user-images.githubusercontent.com/34500301/85055811-ccba8d00-b1bb-11ea-885b-2791ad2545bd.png)

**Comment by brianfeucht** [comment]
@DevGenesis95 based of https://github.com/hardkoded/puppeteer-sharp/issues/1502 it sounds like you got this working.  Feel free to reopen if you continue to run into build issues
