### ISSUE TITLE
Upgrade to PuppeteerSharp 2.0.3

### ISSUE THREAD

**Issue by kblok** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#49]
This project looks super cool!! Thank you for your hard work here.
Any plans to make this project work using PuppeteerSharp 2.0.3?

**Comment by kblok** [comment]
@brianfeucht But we don't have Chromium rev706915 packed in the latest version right?
Just asking

**Comment by brianfeucht** [comment]
I'm just stealing builds from this package:
https://github.com/alixaxel/chrome-aws-lambda#versioning

`1.0.1.39` uses `3.1.0` which is a build of chromium `756035 (83.0.4103.0)`

I need to come up with a way of versioning this to make that easier to track...

**Comment by kblok** [comment]
Cool, good to know! :)
