### ISSUE TITLE
Update puppeteer package

### ISSUE THREAD

**Issue by inicolay** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#56]
can you please update the pupeteersharp package on this?

**Comment by brianfeucht** [comment]
@inicolay we purposely do not update the package to avoid forcing upgrades downstream.  You are free to use the latest version by adding the newest release to your own project.

If you are seeing breaking API changes please let me know and I'm happy to take a look.

**Comment by inicolay** [comment]
when i try to use LaunchAsync with options i get an error Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Launcher.LaunchAsync(PuppeteerSharp.LaunchOptions)'.: MissingMethodException
   at HeadlessChromium.Puppeteer.Lambda.Dotnet.HeadlessChromiumPuppeteerLauncher.LaunchAsync(String[] chromeArgs)

**Comment by brianfeucht** [comment]
@inicolay thanks! Looks like this [PR](https://github.com/hardkoded/puppeteer-sharp/pull/1498) moved some 🧀 and introduced a breaking change.  I'll have a new build for you shortly.

**Comment by inicolay** [comment]
Thank you, appears to be working now.
