### ISSUE TITLE
The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by gprakashgartner** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#63]
Unable to run this on my local machine.
Machine details as below.

OS - Windows 10 Enterprise x64.

I am guessing this is because the executable is not compatible for Windows OS. Any suggestions would be helpful.

**Comment by brianfeucht** [comment]
Hi @gprakashgartner.  I'm sorry I am just seeing this issue now.  This project is specifically targeting running on the linux images used for AWS Lambda.  If you need to run on Windows you should be able to just use the [Puppeteer-Sharp](https://github.com/hardkoded/puppeteer-sharp) library directly without needing to reference this project.

**Comment by gprakashgartner** [comment]
Hello @brianfeucht . Yes I figured that out as I already had mentioned my suspicions in my query. This issue should be marked closed. On another note, I was wondering if it was possible to create an AWS lambda layer using this package. Could be a good thing. I'm curious to learn your thoughts.

**Comment by brianfeucht** [comment]
@gprakashgartner we have talked about it as we are getting dangerously close to the 100MB limit on our own consumers of this.  Most likely we will probably end up going the docker route instead.

**Comment by gprakashgartner** [comment]
@brianfeucht Cool. If there's a conversation/thread going on around that, please share so I can follow it. Thanks.
