### ISSUE TITLE
Failure on creating aws lambda layer

### ISSUE THREAD

**Issue by mmitushevskiMelon** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#77]
manifest.xml file contains the HeadlessChromium.PuppeteerLambda.Dotnet nuget package:
```
<ItemGroup> 
     <PackageReference Include="HeadlessChromium.Puppeteer.Lambda.Dotnet" Version="1.0.1.54" />
  </ItemGroup>
```

on exec the following command: 
 dotnet lambda publish-layer test_layer -sb <bucket_name> --region <aws_region> --layer-type runtime-package-store --package-manifest manifest.xml 

it fails with the error:
 error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 3 item(s). They must have the same number of items.

**Comment by brianfeucht** [comment]
@mmitushevskiMelon if you are building an AWS layer, it is probably best to not use this project.  Instead you will want to look at the project we are extracting the chrome executable from [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda).  They have instruction for [building a layer](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer).  

This project keeps the chrome executable with the .NET deployable and extracts it at run time.  So isn't really a great fit for what you are trying to do.

**Comment by mmitushevskiMelon** [comment]
@brianfeucht can you please share why it fails ? I would like to put all of the nuget packages in a layer not only this one:

**Comment by iambiswa25** [comment]
Hi @brianfeucht  is there any alternative as the package is big for Lambda function and it shows 
`Request must be smaller than 70167211 bytes for the CreateFunction operation` error while deploying.

**Comment by brianfeucht** [comment]
@iambiswa25 take a look at https://github.com/Sparticuz/chromium

This is the binary we are using for this project.  One of the artifacts the Sparticuz project provides is a lambda layer.  You should be able to add this layer to your lambda.  

Once you have the layer packaged up into your lambda you should be able to steal the BrowserLauncher code we have here to start Chromium and configure Puppeteer Dotnet.  No need to take a dependency on this project. 

The other option is to upload the zip to S3 and then use that to create your function.  This is what we do at Litmus. 

Chromium is a big binary 😁
