### ISSUE TITLE
Runing Lambda function net core 3.1 locally I get this error Could not find file amazon.lmabda.tresttool.3.1

### ISSUE THREAD

**Issue by cmkaus** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#82]
The code worked fine when i published into aws. 
But when I try to run it locally I get the exception "**Could not find  file C:\\...\\.donet\\tooles\\.store\\amazon.lambda.testtool 3.1"**

Does this happen to anyone else?
Can anyone else run the code locally 

Thanks in advance.

**Comment by brianfeucht** [comment]
You will likely run into problems running this locally as the chromium binary is built specifically to run on the Linux image AWS uses for Lambda.  You may be able to put together a Linux WSL build that allows you to run there, but you will not have much luck getting this to run on Windows directly.

To run locally you will want to just use Puppeteer directly.
