### ISSUE TITLE
Lambda .NET 6 runtime support

### ISSUE THREAD

**Issue by AlexSmolyar** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#94]
.NET Core 3.1 is out of support from December 13, 2022.
Any plans to make this project work using Lambda with .NET 6?

**Comment by brianfeucht** [comment]
@AlexSmolyar this may just work depending on what AWS did with the base image for the .NET 6 [runtime](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/).  I may not have time to get to this for a month or two.  Have you tried deploying this to the newer runtime?

**Comment by AlexSmolyar** [comment]
@brianfeucht thanks for quick reply!
Yes, I tried to deploy it with 6 version, but unfortunately it doesn't work(

**Comment by brianfeucht** [comment]
Ok thanks for detail.  We will look into it and hopefully get an update out soon.

**Comment by brianfeucht** [comment]
@AlexSmolyar I got a chance to look at this a bit today.  The latest build [1.1.065](https://www.nuget.org/packages/HeadlessChromium.Puppeteer.Lambda.Dotnet/1.1.0.65) ran without errors on the .NET 6.0 lambda runtime.  

I have an issue in our implementation we are working through.  Not clear if this is a chromium/puppeteer issue or something else.  Once we figure out what is going on I can give an update.  

Either way, this build may resolve the issue you were running into.

**Comment by AlexSmolyar** [comment]
@brianfeucht, thank you!
I've also checked from my side as well. It turned out that Lambda on .net 6.0 fails only with arm64 architecture. When launching the browser - an error occurs:
<html>
<body>


---> System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/tmp/chromium' with working directory '/var/task'. Exec format error
--
  | 2023-01-20T12:24:02.265+02:00 | at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
  | 2023-01-20T12:24:02.265+02:00 | at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
  | 2023-01-20T12:24:02.265+02:00 | at System.Diagnostics.Process.Start()
  | 2023-01-20T12:24:02.265+02:00 | at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 68


</body>
</html>

With x86_64 it works as expected .I don't know the reason why it works on x86_64 but not on arm64 yet. Will continue investigation

**Comment by brianfeucht** [comment]
This is expected.  Our upstream lib does not yet have ARM support.  There is an [open PR](https://github.com/Sparticuz/chrome-aws-lambda/pull/11) for that now.  You'll have to run as x86_64 if you want to use this library until that is merged.  I'll get our documentation updated.  

Thanks for your help looking at .NET 6
